services:
  postgres:
    image: postgres:latest
    container_name: tessera
    environment:
      POSTGRES_DB: tessera
      POSTGRES_USER: tessera
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
